import { describe, expect, it } from "vitest";
import { detectSlicer, parseDurationToSeconds, transcodeMetadata } from "./transcoder.js";

describe("parseDurationToSeconds", () => {
  it("parses the OrcaSlicer estimate format", () => {
    expect(parseDurationToSeconds("1h 39m 52s")).toBe(5992);
  });
  it("parses days and bare minutes", () => {
    expect(parseDurationToSeconds("1d 2h 3m 4s")).toBe(93784);
    expect(parseDurationToSeconds("99m")).toBe(5940);
  });
});

const ORCA = [
  "; generated by OrcaSlicer 2.0",
  "; estimated printing time (normal mode) = 1h 39m 52s",
  "; filament used [mm] = 5894.33",
  "; total filament used [g] = 17.58",
  "; total layer number: 450",
  "M73 P0 R99",
  "G28",
  "M73 P1 R98",
].join("\n");

describe("transcodeMetadata (§4A)", () => {
  it("injects the Anker/Cura headers from Orca's embedded estimate", () => {
    const r = transcodeMetadata(ORCA);
    expect(r.changed).toBe(true);
    expect(r.injected.timeSeconds).toBe(5992);
    expect(r.content).toMatch(/^;TIME:5992s$/m);
    expect(r.content).toMatch(/^;Filament used: 5894\.33mm$/m);
    expect(r.content).toMatch(/^;Filament weight: 17\.58g$/m);
  });

  it("leaves M73 progress commands untouched", () => {
    const r = transcodeMetadata(ORCA);
    expect(r.content).toMatch(/M73 P0 R99/);
    expect(r.content).toMatch(/M73 P1 R98/);
  });

  it("is a no-op on a natively-sliced file that already has ;TIME:", () => {
    const native = ";TIME:8573s\n;Filament used: 14876.3mm\nG28\n";
    const r = transcodeMetadata(native);
    expect(r.changed).toBe(false);
    expect(r.content).toBe(native);
  });
});

describe("detectSlicer", () => {
  it("identifies OrcaSlicer and native AnkerMake", () => {
    expect(detectSlicer(ORCA)).toBe("orca");
    expect(detectSlicer(";TIME:100s\nG28")).toBe("ankermake");
  });
});
