service: graff-server
frameworkVersion: '3'

plugins:
  - serverless-offline
  - serverless-esbuild

package:
  patterns:
    - 'node_modules/.prisma/client/**'
    - '!node_modules/.prisma/client/libquery_engine-*'
    - 'node_modules/.prisma/client/libquery_engine-rhel-*'
    - '!node_modules/prisma/libquery_engine-*'
    - '!node_modules/@prisma/engines/**'

provider:
  name: aws
  runtime: nodejs16.x
  region: us-west-2

functions:
  interface:
    handler: graphql.graphqlHandler
    environment:
      DATABASE_URL: ${env:DATABASE_URL}
    url: true
      # authorizer: aws_iam