name: Production Deploy

on:
  push:
    branches:
      - 'main'

jobs:
  npm-Install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm install
  Prisma-Generate:
    runs-on: ubuntu-latest
    steps:
      - run:
        working-directory: graff
        command: npx --yes prisma generate
