name: Production Deploy

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    name: Production Build 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm install
      - name: Generate prisma client
        run: npx --yes prisma generate
        working-directory: ./graff
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npx --yes serverless deploy
        working-directory: ./graff
        name: Deploy serverless function

